image: debian

stages:
  - build
  - test
  - release

build:
  stage: build
  before_script:
    - apt-get update && apt-get -qq install clang mingw-w64 git make zip > /dev/null
  script:
    - make
  artifacts:
    name: "$CI_COMMIT_SHORT_SHA-$CI_JOB_NAME"
    paths:
      - build
  only:
    refs:
      - master

test:
  allow_failure: true
  stage: test
  dependencies:
    - build
  before_script:
    - apt-get update && apt-get -qq install make wine unzip > /dev/null
    - dpkg --add-architecture i386 && apt-get update && apt-get -qq install wine32 > /dev/null
  script:
    - ls
    - make run-tests
  only:
    refs:
      - master

release:
  stage: release
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  before_script:
    - apt-get update && apt-get -qq install zip > /dev/null
  script:
    - mv build/bemanitools.zip ./bemanitools.zip
    - find . -mindepth 1 ! -regex '^./bemanitools.zip' -delete
    - unzip bemanitools.zip
    - rm bemanitools.zip
  artifacts:
    name: "$CI_COMMIT_SHORT_SHA-$CI_JOB_NAME"
    paths:
      - ./*
  only:
    refs:
      - master
